### ISSUE TITLE
Roundtripping emphasis like plain text results in emphasis

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#25]
### Subject of the issue

```markdown
(____
```

is stringified as:

```markdown
(\__\__
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.5
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
(____
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
(\__\__
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "emphasis",
                    "children": [
                        {
                            "type": "text"
                        }
                    ]
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by ChristianMurphy** [comment]
Some other examples

```markdown
[____
```

```markdown
<____
```

```markdown
-____
```

**Comment by andymatuschak** [comment]
I ran into this tonight and briefly looked into it. I fear it'll be somewhat tricky to fix. My understanding is that what we really want here is to make the "safe escape" semantics, as they apply to `_` and `*`, obey the delimiter run rules described [here in the CommonMark spec](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis). That is, the reason that these underscores should not be escaped is that they will not be interpreted as emphasis characters. Unfortunately, I don't think those delimiter run rules can be encoded in a regular expression—or at least, it'd be one gnarly regex! I wonder if a facility for a more sophisticated safe matcher will be necessary.

**Comment by wooorm** [comment]
Did you find a real-world human-authored example where this was going wrong? The examples by @ChristianMurphy were generated by a computer, and all look a bit weird.

Was the problem roundtripping? Or too many ugly escapes?

Here’s my ideas on this: it’s a two part problem:
1. Is this character part of a delimiter run
2. Is there another delimiter run that matches it

I think we can skip the second point.

But point 1 is a bit complex because:

- it needs to know about more characters, the escaping currently only gets one previous and next character, whereas here we need to know about potentially many previous and next characters?
- Escaping one emphasis/strong(/strikethrough) marker affects the next: The delimiter run in ` ***`, `a***`, and `-***` used to be preceded by unicode whitespace, unicode alphanumeric, and unicode punctuation, but if the first asterisk is escaped it’s now a run preceded by unicode punctuation
- the rules for `_` are more complex, as it’s allowed in more cases.

Here’ a sample of showing escapes: https://spec.commonmark.org/dingus/?text=Separate%20paragraphs%3A%0A%0Aa%20*%20is%20this%20emphasis%3F%20*%0A%0Aa%20**%20is%20this%20emphasis%3F%20**%0A%0Aa%20***%20is%20this%20emphasis%3F%20***%0A%0Aa%20*%5C*%20is%20this%20emphasis%3F%20*%5C*%0A%0Aa%20%5C**%20is%20this%20emphasis%3F%20%5C**%0A%0Aa%20**%5C*%20is%20this%20emphasis%3F%20**%5C*%0A%0Aa%20*%5C**%20is%20this%20emphasis%3F%20*%5C**%0A%0AOne%20paragraph%3A%0A%0Aa%20*%20is%20this%20emphasis%3F%20*%0Aa%20**%20is%20this%20emphasis%3F%20**%0Aa%20***%20is%20this%20emphasis%3F%20***%0Aa%20*%5C*%20is%20this%20emphasis%3F%20*%5C*%0Aa%20%5C**%20is%20this%20emphasis%3F%20%5C**%0Aa%20**%5C*%20is%20this%20emphasis%3F%20**%5C*%0Aa%20*%5C**%20is%20this%20emphasis%3F%20*%5C**%0A.

**Comment by wooorm** [comment]
@andymatuschak Would love to get access to the failing input you had, to see if they now work with the simple solution in GH-43.

**Comment by andymatuschak** [comment]
I noticed this with text with faux "fill in the blank" spans:

```
Once activated, a service worker ______, then transitions to idle. From that state, it’ll handle fetch or message events until it eventually terminates.
```

**Comment by wooorm** [comment]
Thanks, added that as a test

**Comment by wooorm** [comment]
Solved, thanks both!
