### ISSUE TITLE
regression in 1.5 release

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-to-markdown#58]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown 1.5

### Steps to reproduce

create a simple tree with:
```
root([
  heading(1, text('Title')),
  text('Hello, world.'),
]);
````

and generate markdown with 1.4 and 1.5. the results are different.

While I understand, that the MDAST might not be valid in respect to the commonmark spec, I think that changing the context based on the child list in `root` should have been made in a major release...

### Expected behavior

it should produce the same output.

### Actual behavior

with 1.4 it produces:
```
# Title

Hello, world.
```

with 1.5 it produces:
```
# TitleHello, world.
```

### Affected runtime and version

node@18

**Comment by wooorm** [comment]
> MDAST might not be valid

Why do you have invalid mdast?

Reminds me a bit of this: https://xkcd.com/1172/.

---

I consider this change a bugfix. Root nodes can contain any type of content, so long as it is of the [same kind](https://github.com/syntax-tree/mdast#root). Previously, all content was treated as blocks, which is incorrect. Because in markdown there are often unknown nodes (from the many extensions), the algorithm checks for explicit phrasing nodes (e.g., text or strong or so are always phrasing). When there are known phrasing nodes, the content is thus guaranteed to be phrasing.
