### ISSUE TITLE
Cannot run inside WebWorker

### ISSUE THREAD

**Issue by siefkenj** [syntax-tree/mdast-util-to-markdown#60]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2

### Steps to reproduce

In a browser console, run
```
response = `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2'; console.log("hi there")`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob), {type: "module"});
```

### Expected behavior

`"hi there"` should be printed to the console.

### Actual behavior

An error
```
index.dom.js:5 Uncaught ReferenceError: document is not defined
    at index.dom.js:5:17
```
is displayed.

### Affected runtime and version

Firefox 118 / Chrome 116

**Comment by ChristianMurphy** [comment]
Welcome @siefkenj! 👋 
Sorry you ran into a spot of trouble.
A few things to note here:
1. this error does not come from `mdast-util-to-markdown` itself, running your example in Firefox traces it back to it's actual root
    ```
    ReferenceError: document is not defined [decode-named-character-reference.mjs:2:7](https://esm.sh/v132/decode-named-character-reference@1.0.2/es2022/decode-named-character-reference.mjs)
    <anonymous> https://esm.sh/v132/decode-named-character-reference@1.0.2/es2022/decode-named-character-reference.mjs:2
    ```
2. `decode-named-character-reference` does offer a `webworker` version https://github.com/wooorm/decode-named-character-reference/blob/4347630741f82d7d4c7fb38763ba158951b2a1be/package.json#L36, the issue is with your configuration/build tool for not choosing the `webworker` version (ref: https://github.com/wooorm/parse-entities/issues/19)
3. esh.sh already supports this with the `?worker` option documented in the readme https://github.com/esm-dev/esm.sh#web-worker
4. If you are experience an issue with esh.sh's ability to build the code, please report it to them

**Comment by siefkenj** [comment]
Thank you for the information. It would be really nice if an error with a little more information could be thrown in the case of a misloaded module :-).

As per your suggestion, I tried
```javascript
response = `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?worker'; console.log("hi there")`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob), {type: "module"}); 
```

but it still errors...

**Comment by remcohaszing** [comment]
`decode-named-character-reference` uses the `worker` export condition. This is not the same as loading a module as a worker using the `?worker` query parameter.

The problem is that esm.sh does resolve the `browser` condition, but not the `worker` condition. You can make it do so using `https://esm.sh/mdast-util-to-markdown@2?conditions=worker`

I think it’s a great idea to use the `worker` condition, but it’s not standardized. Maybe we should propose it to https://runtime-keys.proposal.wintercg.org.

**Comment by siefkenj** [comment]
I'm sorry for not including enough context. I am running Firefox 118 and Chrome 116 (as stated in the original bug report) on Linux. I am running these commands in the web console on the the page `https://esm.sh/mdast-util-to-markdown@2.1.0`.

The code
```javascript
response = `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?worker'; console.log("hi there")`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob), {type: "module"}); 
```

should print `"hi there"` to the console if it executes correctly. However `"hi there"` is not printed in Firefox or Chrome. No error message is given to me in either browser, but importing a worker-safe module makes `"hi there"` be printed to the console. For example:

```javascript
response = `import React from "https://esm.sh/react@18.2.0";\n console.log("hi there")`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob), {type: "module"}); 
```

Changing the import line `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?worker'` to `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?conditions=worker'` does cause an error `Uncaught ReferenceError: document is not defined` to be printed in Firefox and Chrome. And `"hi there"` is still not printed.

**Comment by ChristianMurphy** [comment]
> `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?conditions=worker'` does cause an error `Uncaught ReferenceError: document is not defined` to be printed in Firefox and Chrome.

This is a bug in esm.sh then, it is not applying the condition as requested

> ```js
> response = `import {toMarkdown} from 'https://esm.sh/mdast-util-to-markdown@2?worker';
> console.log("hi there")`;
> blob = new Blob([response], {type: 'application/javascript'});
> worker = new Worker(URL.createObjectURL(blob), {type: "module"}); 
> ```
> should print "hi there" to the console if it executes correctly. However "hi there" is not printed in Firefox or Chrome. No error message is given to me in either browser, but importing a worker-safe module makes "hi there" be printed to the console.

Please read the docs that were shared on `?worker` https://github.com/esm-dev/esm.sh#web-worker
esm.sh's worker mode has already placed the code inside a webworker, and returns a worker factory as the default export.
You are pulling from a named export, that does not exist in esm.sh's worker mode.

---

To reiterate from the first response

> If you are experience an issue with esm.sh's ability to build the code, please report it to them

https://github.com/esm-dev/esm.sh/issues is their issue tracker.
